import prettier from "eslint-config-prettier";
// Generated by the @nuxt/eslint module -- carries Nuxt's auto-import globals
// (ref, useRuntimeConfig, definePageMeta, ...) that a hand-written flat
// config can't know about statically.
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt(prettier, {
  rules: {
    "vue/multi-word-component-names": "off",
  },
});
